# Reusable template for uploading NuGet packages

parameters:
    - name: product
      type: string
    - name: condition
      type: string
      default: "true"

steps:
    - task: PublishPipelineArtifact@1
      displayName: Upload ${{ parameters.product }} NuGet packages
      condition: ${{ parameters.condition }}
      inputs:
          targetPath: $(Build.SourcesDirectory)/artifacts/nupkg
          artifact: ${{ parameters.product }}-packages
          publishLocation: pipeline
